require ('./schema.js');
require ('./index.js');
require ('./lookupStreamTest.js');
require ('./localPipResolverTest.js');
require ('./pip/components/extractFieldsTest.js');
require ('./pip/components/extractFieldsLocalizedNameTest.js');
require ('./pip/components/simplifyGeometryTest.js');
require ('./pip/components/filterOutUnimportantRecordsTest.js');
require ('./pip/components/filterOutPointRecordsTest.js');
